name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone Wiki
        run: |
          git clone https://github.com/<your-username>/<your-repo>.wiki.git wiki

      - name: Copy Documentation to Wiki
        run: |
          cp docs/*.md wiki/
          cd wiki
          git add .
          git commit -m "Update Wiki from main repository"
          git push
