name: Update Wiki

on:
  push:
    branches:
      - main
      - hotfix/*    # Include all branches prefixed with 'hotfix/'

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone Wiki
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${REPO}.wiki.git wiki

      - name: Copy Documentation to Wiki
        run: |
          cp docs/*.md wiki/
          cd wiki
          git add .
          git commit -m "Update Wiki from hotfix branch (${GITHUB_REF})"
          git push
